site_name: Fairfax For Devs - API
theme:
  name: readthedocs
  highlightjs: true
  locale: pt_BR
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
    - Introdução:
        - Sobre a API: '../introducao/sobre-a-api'
        - Ambientes: '../introducao/ambientes'
        - Configurações: '../introducao/configuracoes'
    - 'Produtos':
        - 'Bike': 
            - 'Sobre o Produto': '../produtos/bike/sobre-o-produto'
            - 'Criar Cotação': '../produtos/bike/criar-cotacao'
            - 'Criar Proposta': '../produtos/bike/criar-proposta'
            - 'Realizar Checkout': '../produtos/bike/realizar-checkout'
